cc_test(
    name = "action_test",
    srcs = ["test-action.cc"],
    deps = ["//:rules", "@googletest//:gtest_main"],
    linkopts = ["-ldl"],
)

cc_test(
    name = "game-state-history_test",
    srcs = ["test-game-state-history.cc"],
    deps = ["//:rules", "@googletest//:gtest_main"],
    linkopts = ["-ldl"],
)
