package(
    default_visibility = ["//visibility:public"],
)

exports_files(["e2e_test.sh", "stechec2_replay.sh.tpl", "stechec2.bzl"])

py_binary(
    name = "stechec2-run",
    srcs = ["stechec2-run.py"],
)
