package(
    default_visibility = ["//visibility:public"],
)

exports_files(["e2e_test.sh", "stechec2-run.sh", "stechec2.bzl", "replay_test.sh"])

py_binary(
    name = "stechec2-run",
    srcs = ["stechec2-run.py"],
)
